### ISSUE TITLE
File not generated as array

### ISSUE THREAD

**Issue by kamiljozwik** [yhnavein/swaggie#19]
This API code:

![image (4)](https://user-images.githubusercontent.com/26552385/121156918-6950c180-c849-11eb-9da5-d67ef3fee7cd.png)

is generating this result (it is `File`, but should be `File[]`):

![File](https://user-images.githubusercontent.com/26552385/121156858-5b9b3c00-c849-11eb-9770-af4f498c1569.PNG)

**Comment by PatrykPlewaOfficial** [comment]
@kamiljozwik You can try using [IFormFileCollection](https://docs.microsoft.com/pl-pl/dotnet/api/microsoft.aspnetcore.http.iformfilecollection?view=aspnetcore-5.0) on the API side, instead of `IEnumerable<>`.
