### ISSUE TITLE
"formDataBody" stops to use `.toString()` method

### ISSUE THREAD

**Issue by kamiljozwik** [yhnavein/swaggie#22]
With version `0.4.11`,  `formDataBody.append(...)` was using `.toString()` method on non-string data 👇
![image](https://user-images.githubusercontent.com/26552385/135604976-002fc3b4-50b9-4045-82c9-72981f9984a6.png)

The latest version is no longer doing it 😥 👇
![image](https://user-images.githubusercontent.com/26552385/135605390-675fec35-f54e-4696-bddc-62a17d7b4730.png)

**Comment by PatrykPlewaOfficial** [comment]
Possibly caused by this fix
https://github.com/yhnavein/swaggie/commit/db91b328fb21162cf27a4073bd12f2119c3f1d23#diff-8329d6668e530601c48be7356d1832798b80457626a137c108a261b0e9af80c4

**Comment by PatrykPlewaOfficial** [comment]
My suggestion is to extend [the line](https://github.com/yhnavein/swaggie/blob/70b7e83647f11ab5d2c764f9fa068c52e110d6cf/templates/axios/operation.ejs#L24) and add another if to check whether the type is string or blob. If not then add `toString()`.

**Comment by yhnavein** [comment]
Fixed in [v0.6.6](https://github.com/yhnavein/swaggie/releases/tag/v0.6.6)

**Comment by PatrykPlewaOfficial** [comment]
The fix was insufficient because it breaks the files' support.
Here's my fix. Please take a look :)

https://github.com/yhnavein/swaggie/pull/23
